baseURL = "https://example.com"
defaultContentLanguage = "en"
disqusShortname = "yourdiscussshortname"
enableGitInfo = true
languageCode = "en-us"
theme = "cupper-hugo-theme"
title = "Keix Koffee"
[imaging]
quality = 99
[[menu.nav]]
name = "RSS"
url = "/index.xml"
weight = 5
[[menu.nav]]
name = "About"
url = "/about/"
weight = 4
[[menu.nav]]
name = "Tags"
url = "/tags/"
weight = 3
[[menu.nav]]
name = "Blog"
url = "/posts/"
weight = 2
[[menu.nav]]
name = "Home"
url = "/"
weight = 1
[params]
codePenUser = "someUser"
dateFormat = "Jan 2, 2006"
description = "An accessibility-friendly Hugo theme, ported from the [original Cupper](https://github.com/ThePacielloGroup/cupper) project."
footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."
homeMetaContent = "An accessibility-friendly Hugo theme, ported from the original Cupper project."
katex = true
[permalinks]
post = "/:filename/"
[taxonomies]
tag = "tags"
